[package]
name = "hollower233/group-join-reward-service"
description = "Secure, one-time group-join rewards for Roblox experiences."
version = "0.1.1"
license = "MIT"
authors = ["Hollower233"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
repository = "https://github.com/Hollower233/group-join-reward-service"

[dependencies]
Net = "sleitnick/net@0.2.0"
